//! Klar interop for Kira.
//!
//! Generates C header files from Kira modules that Klar can import
//! via its FFI `extern` blocks. Both languages use standard C calling
//! conventions, so the interop boundary is a C ABI.
//!
//! Usage:
//!   kira build mylib.ki            -> produces mylib.c
//!   cc -c mylib.c -o mylib.o       -> compile to object file
//!   (Klar imports via extern block pointing to mylib.o)

const std = @import("std");
const Allocator = std.mem.Allocator;
const ir = @import("../ir/ir.zig");

/// Map a Kira IR type to a C type string for header generation.
pub fn kiraToCType(kira_type: []const u8) []const u8 {
    if (std.mem.eql(u8, kira_type, "i32") or std.mem.eql(u8, kira_type, "int")) return "int32_t";
    if (std.mem.eql(u8, kira_type, "i64")) return "int64_t";
    if (std.mem.eql(u8, kira_type, "f64") or std.mem.eql(u8, kira_type, "float")) return "double";
    if (std.mem.eql(u8, kira_type, "bool")) return "bool";
    if (std.mem.eql(u8, kira_type, "string")) return "const char*";
    if (std.mem.eql(u8, kira_type, "void")) return "void";
    return "int64_t"; // Default for unknown types
}

/// Map a Kira type name to the corresponding Klar FFI type.
pub fn kiraToKlarType(kira_type: []const u8) []const u8 {
    if (std.mem.eql(u8, kira_type, "i32")) return "i32";
    if (std.mem.eql(u8, kira_type, "i64")) return "i64";
    if (std.mem.eql(u8, kira_type, "f64")) return "f64";
    if (std.mem.eql(u8, kira_type, "bool")) return "Bool";
    if (std.mem.eql(u8, kira_type, "string")) return "CStr";
    if (std.mem.eql(u8, kira_type, "void")) return "Void";
    return "i64";
}

/// Generate a C header file from an IR module.
/// The header declares all public functions with C-compatible signatures.
/// Caller owns the returned slice.
pub fn generateHeader(allocator: Allocator, module: *const ir.Module) ![]u8 {
    var output = std.ArrayListUnmanaged(u8){};
    errdefer output.deinit(allocator);

    // Header guard
    try appendSlice(allocator, &output, "/* Generated by Kira compiler — C header for FFI */\n");
    try appendSlice(allocator, &output, "#ifndef KIRA_MODULE_H\n");
    try appendSlice(allocator, &output, "#define KIRA_MODULE_H\n\n");
    try appendSlice(allocator, &output, "#include <stdint.h>\n");
    try appendSlice(allocator, &output, "#include <stdbool.h>\n\n");
    try appendSlice(allocator, &output, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    // Declare all non-main functions
    for (module.functions.items) |func| {
        const name = func.name orelse continue;
        if (std.mem.eql(u8, name, "main")) continue;

        // Return type — use int64_t as default (matches codegen)
        try appendSlice(allocator, &output, "int64_t ");
        try appendFmt(allocator, &output, "{s}(", .{name});

        // Parameters
        if (func.params.len == 0) {
            try appendSlice(allocator, &output, "void");
        } else {
            for (func.params, 0..) |param, i| {
                if (i > 0) try appendSlice(allocator, &output, ", ");
                try appendFmt(allocator, &output, "int64_t {s}", .{param.name});
            }
        }

        try appendSlice(allocator, &output, ");\n");
    }

    try appendSlice(allocator, &output, "\n#ifdef __cplusplus\n}\n#endif\n\n");
    try appendSlice(allocator, &output, "#endif /* KIRA_MODULE_H */\n");

    return output.toOwnedSlice(allocator);
}

/// Generate a Klar extern block that can import functions from a Kira module.
/// Caller owns the returned slice.
pub fn generateKlarExternBlock(allocator: Allocator, module: *const ir.Module) ![]u8 {
    var output = std.ArrayListUnmanaged(u8){};
    errdefer output.deinit(allocator);

    try appendSlice(allocator, &output, "// Generated Klar extern block for Kira module\n");
    try appendSlice(allocator, &output, "extern {\n");

    for (module.functions.items) |func| {
        const name = func.name orelse continue;
        if (std.mem.eql(u8, name, "main")) continue;

        try appendFmt(allocator, &output, "    fn {s}(", .{name});

        for (func.params, 0..) |param, i| {
            if (i > 0) try appendSlice(allocator, &output, ", ");
            try appendFmt(allocator, &output, "{s}: i64", .{param.name});
        }

        try appendSlice(allocator, &output, ") -> i64\n");
    }

    try appendSlice(allocator, &output, "}\n");

    return output.toOwnedSlice(allocator);
}

fn appendSlice(allocator: Allocator, output: *std.ArrayListUnmanaged(u8), s: []const u8) !void {
    try output.appendSlice(allocator, s);
}

fn appendFmt(allocator: Allocator, output: *std.ArrayListUnmanaged(u8), comptime fmt: []const u8, args: anytype) !void {
    const formatted = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(formatted);
    try output.appendSlice(allocator, formatted);
}

// --- Tests ---

test "kiraToCType mappings" {
    try std.testing.expectEqualStrings("int32_t", kiraToCType("i32"));
    try std.testing.expectEqualStrings("int64_t", kiraToCType("i64"));
    try std.testing.expectEqualStrings("double", kiraToCType("f64"));
    try std.testing.expectEqualStrings("bool", kiraToCType("bool"));
    try std.testing.expectEqualStrings("const char*", kiraToCType("string"));
    try std.testing.expectEqualStrings("void", kiraToCType("void"));
    try std.testing.expectEqualStrings("int64_t", kiraToCType("unknown"));
}

test "kiraToKlarType mappings" {
    try std.testing.expectEqualStrings("i32", kiraToKlarType("i32"));
    try std.testing.expectEqualStrings("f64", kiraToKlarType("f64"));
    try std.testing.expectEqualStrings("CStr", kiraToKlarType("string"));
}

test "generateHeader empty module" {
    const allocator = std.testing.allocator;
    var module = ir.Module.init(allocator);
    defer module.deinit();

    const header = try generateHeader(allocator, &module);
    defer allocator.free(header);

    try std.testing.expect(std.mem.indexOf(u8, header, "#ifndef KIRA_MODULE_H") != null);
    try std.testing.expect(std.mem.indexOf(u8, header, "#endif") != null);
}

test "generateHeader with function" {
    const allocator = std.testing.allocator;
    var module = ir.Module.init(allocator);
    defer module.deinit();

    const arena = module.arena.allocator();
    var func = ir.Function.init(arena);
    func.name = "add";
    const params = try arena.alloc(ir.Function.Param, 2);
    params[0] = .{ .name = "a", .value_ref = 0 };
    params[1] = .{ .name = "b", .value_ref = 1 };
    func.params = params;
    try module.functions.append(arena, func);

    const header = try generateHeader(allocator, &module);
    defer allocator.free(header);

    try std.testing.expect(std.mem.indexOf(u8, header, "int64_t add(int64_t a, int64_t b)") != null);
}

test "generateKlarExternBlock" {
    const allocator = std.testing.allocator;
    var module = ir.Module.init(allocator);
    defer module.deinit();

    const arena = module.arena.allocator();
    var func = ir.Function.init(arena);
    func.name = "multiply";
    const params = try arena.alloc(ir.Function.Param, 2);
    params[0] = .{ .name = "x", .value_ref = 0 };
    params[1] = .{ .name = "y", .value_ref = 1 };
    func.params = params;
    try module.functions.append(arena, func);

    const block = try generateKlarExternBlock(allocator, &module);
    defer allocator.free(block);

    try std.testing.expect(std.mem.indexOf(u8, block, "extern {") != null);
    try std.testing.expect(std.mem.indexOf(u8, block, "fn multiply(x: i64, y: i64) -> i64") != null);
}
