//! C code generation backend for Kira.
//!
//! Translates Kira IR into C source code that can be compiled with any
//! standard C compiler (gcc, clang).
//!
//! Each IR function becomes a C function. SSA values become local variables.
//! Basic blocks become labeled sections with goto-based control flow.
//!
//! Limitations (scaffolding phase):
//! - All values use a uniform `kira_int` (i64) representation. Float operations
//!   use bit-punning; strings cast through intptr_t. This is 64-bit only.
//! - Compound types (tuples, arrays, records, closures) emit `abort()` stubs.
//!   The Zig runtime module (`src/runtime/`) defines the proper representations
//!   but is not yet linked into the C output.

const std = @import("std");
const Allocator = std.mem.Allocator;
const ir = @import("ir/ir.zig");
const Module = ir.Module;
const Function = ir.Function;
const Instruction = ir.Instruction;
const Terminator = ir.Terminator;
const ValueRef = ir.ValueRef;
const BlockId = ir.BlockId;

pub const CodeGenError = error{
    OutOfMemory,
    UnsupportedInstruction,
    InvalidIR,
};

/// C code generator that emits C source from Kira IR.
pub const CCodeGen = struct {
    allocator: Allocator,
    /// Output buffer for generated C code.
    output: std.ArrayListUnmanaged(u8),
    /// Current indentation level.
    indent_level: u32,
    /// Reference to the module being generated (set during generateModule).
    current_module: ?*const Module,

    pub fn init(allocator: Allocator) CCodeGen {
        return .{
            .allocator = allocator,
            .output = .{},
            .indent_level = 0,
            .current_module = null,
        };
    }

    pub fn deinit(self: *CCodeGen) void {
        self.output.deinit(self.allocator);
    }

    /// Get the generated C source code.
    pub fn getOutput(self: *const CCodeGen) []const u8 {
        return self.output.items;
    }

    /// Generate C code for an entire IR module.
    pub fn generateModule(self: *CCodeGen, module: *const Module) CodeGenError!void {
        self.current_module = module;
        try self.emitPreamble();
        try self.emitTypeDecls(module);
        try self.emitFunctionDeclarations(module);
        try self.emitConstants(module);
        for (module.functions.items) |*func| {
            try self.emitFunction(func);
        }
    }

    // ----------------------------------------------------------------
    // Preamble
    // ----------------------------------------------------------------

    fn emitPreamble(self: *CCodeGen) CodeGenError!void {
        try self.write("/* Generated by Kira compiler */\n");
        try self.write("#include <stdint.h>\n");
        try self.write("#include <stdbool.h>\n");
        try self.write("#include <stdio.h>\n");
        try self.write("#include <stdlib.h>\n");
        try self.write("#include <string.h>\n\n");
        try self.write("/* Kira runtime types */\n");
        try self.write("typedef int64_t kira_int;\n");
        try self.write("typedef double kira_float;\n");
        try self.write("typedef bool kira_bool;\n");
        try self.write("typedef uint32_t kira_char;\n");
        try self.write("typedef const char* kira_string;\n");
        try self.write("typedef void kira_void;\n\n");
        try self.write("/* Kira runtime IO functions */\n");
        try self.write("static void kira_println(kira_string s) { printf(\"%s\\n\", s); }\n");
        try self.write("static void kira_print(kira_string s) { printf(\"%s\", s); }\n");
        try self.write("static void kira_println_int(kira_int n) { printf(\"%lld\\n\", (long long)n); }\n");
        try self.write("static void kira_print_int(kira_int n) { printf(\"%lld\", (long long)n); }\n\n");
    }

    // ----------------------------------------------------------------
    // Type declarations
    // ----------------------------------------------------------------

    fn emitTypeDecls(self: *CCodeGen, module: *const Module) CodeGenError!void {
        if (module.type_decls.items.len == 0) return;
        try self.write("/* Type declarations */\n");
        for (module.type_decls.items) |td| {
            switch (td.kind) {
                .sum_type => |st| {
                    try self.write("/* Sum type: ");
                    try self.write(td.name);
                    try self.write(" */\n");
                    try self.write("typedef struct {\n");
                    self.indent_level += 1;
                    try self.writeIndent();
                    try self.write("uint32_t tag;\n");
                    // Find max field count across variants
                    var max_fields: u32 = 0;
                    for (st.variants) |v| {
                        if (v.field_count > max_fields) max_fields = v.field_count;
                    }
                    if (max_fields > 0) {
                        try self.writeIndent();
                        try self.writeFmt("kira_int fields[{d}];\n", .{max_fields});
                    }
                    self.indent_level -= 1;
                    try self.write("} kira_");
                    try self.write(td.name);
                    try self.write(";\n\n");

                    // Emit tag constants
                    for (st.variants) |v| {
                        try self.writeFmt("#define TAG_{s}_{s} {d}\n", .{ td.name, v.name, v.tag });
                    }
                    try self.write("\n");
                },
                .product_type => |pt| {
                    try self.write("/* Record type: ");
                    try self.write(td.name);
                    try self.write(" */\n");
                    try self.write("typedef struct {\n");
                    self.indent_level += 1;
                    for (pt.fields) |f| {
                        try self.writeIndent();
                        try self.writeFmt("kira_int {s};\n", .{f.name});
                    }
                    self.indent_level -= 1;
                    try self.write("} kira_");
                    try self.write(td.name);
                    try self.write(";\n\n");
                },
            }
        }
    }

    // ----------------------------------------------------------------
    // Forward declarations
    // ----------------------------------------------------------------

    fn emitFunctionDeclarations(self: *CCodeGen, module: *const Module) CodeGenError!void {
        if (module.functions.items.len == 0) return;
        try self.write("/* Forward declarations */\n");
        for (module.functions.items) |*func| {
            try self.write("kira_int ");
            try self.emitFunctionName(func);
            try self.write("(");
            for (func.params, 0..) |p, i| {
                if (i > 0) try self.write(", ");
                try self.writeFmt("kira_int {s}", .{p.name});
            }
            if (func.params.len == 0) try self.write("void");
            try self.write(");\n");
        }
        try self.write("\n");
    }

    // ----------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------

    fn emitConstants(self: *CCodeGen, module: *const Module) CodeGenError!void {
        if (module.constants.items.len == 0) return;
        try self.write("/* Constants */\n");
        for (module.constants.items) |c| {
            try self.writeFmt("static const kira_int kira_const_{s} = ", .{c.name});
            switch (c.value) {
                .integer => |v| try self.writeFmt("{d}", .{v}),
                .float => |v| try self.writeFmt("{d}", .{v}),
                .boolean => |b| try self.write(if (b) "1" else "0"),
                .string => |s| {
                    try self.write("(kira_int)(intptr_t)\"");
                    try self.write(s);
                    try self.write("\"");
                },
                .char => |c_val| try self.writeFmt("{d}", .{c_val}),
                .void_val => try self.write("0"),
            }
            try self.write(";\n");
        }
        try self.write("\n");
    }

    // ----------------------------------------------------------------
    // Function emission
    // ----------------------------------------------------------------

    fn emitFunction(self: *CCodeGen, func: *const Function) CodeGenError!void {
        // Function signature
        if (func.is_effect) try self.write("/* effect */ ");
        try self.write("kira_int ");
        try self.emitFunctionName(func);
        try self.write("(");
        for (func.params, 0..) |p, i| {
            if (i > 0) try self.write(", ");
            try self.writeFmt("kira_int {s}", .{p.name});
        }
        if (func.params.len == 0) try self.write("void");
        try self.write(") {\n");
        self.indent_level += 1;

        // Declare all SSA variables
        if (func.instructions.items.len > 0) {
            try self.writeIndent();
            try self.write("kira_int ");
            for (0..func.instructions.items.len) |i| {
                if (i > 0) try self.write(", ");
                try self.writeFmt("v{d}", .{i});
            }
            try self.write(";\n");
        }

        // Emit basic blocks
        for (func.blocks.items) |*blk| {
            try self.emitBlock(func, blk);
        }

        self.indent_level -= 1;
        try self.write("}\n\n");
    }

    fn emitFunctionName(self: *CCodeGen, func: *const Function) CodeGenError!void {
        if (func.name) |name| {
            try self.write("kira_");
            try self.write(name);
        } else {
            try self.write("kira_anon");
        }
    }

    fn emitBlock(self: *CCodeGen, func: *const Function, blk: *const ir.BasicBlock) CodeGenError!void {
        // Block label
        try self.writeIndent();
        try self.writeFmt("bb{d}:;\n", .{blk.id});

        // Instructions
        for (blk.instructions.items) |ref| {
            const inst = func.getInstruction(ref);
            try self.emitInstruction(func, ref, inst);
        }

        // Terminator
        try self.emitTerminator(&blk.terminator);
    }

    // ----------------------------------------------------------------
    // Instruction emission
    // ----------------------------------------------------------------

    fn emitInstruction(self: *CCodeGen, func: *const Function, ref: ValueRef, inst: *const Instruction) CodeGenError!void {
        try self.writeIndent();
        switch (inst.op) {
            .const_int => |c| try self.writeFmt("v{d} = {d};\n", .{ ref, c.value }),
            .const_float => |f| try self.writeFmt("v{d} = *(kira_int*)&(kira_float){{{d}}};\n", .{ ref, f }),
            .const_bool => |b| try self.writeFmt("v{d} = {d};\n", .{ ref, @as(u1, if (b) 1 else 0) }),
            .const_char => |c| try self.writeFmt("v{d} = {d};\n", .{ ref, c }),
            .const_void => try self.writeFmt("v{d} = 0;\n", .{ref}),
            .const_string => |s| try self.writeFmt("v{d} = (kira_int)(intptr_t)\"{s}\";\n", .{ ref, s }),
            .int_binop => |b| {
                const op_str: []const u8 = switch (b.op) {
                    .add => "+",
                    .sub => "-",
                    .mul => "*",
                    .div => "/",
                    .mod => "%",
                };
                try self.writeFmt("v{d} = v{d} {s} v{d};\n", .{ ref, b.left, op_str, b.right });
            },
            .float_binop => |b| {
                const op_str: []const u8 = switch (b.op) {
                    .add => "+",
                    .sub => "-",
                    .mul => "*",
                    .div => "/",
                    .mod => " /* fmod */ %",
                };
                try self.writeFmt("v{d} = v{d} {s} v{d}; /* float */\n", .{ ref, b.left, op_str, b.right });
            },
            .int_neg => |v| try self.writeFmt("v{d} = -v{d};\n", .{ ref, v }),
            .float_neg => |v| try self.writeFmt("v{d} = -v{d}; /* float */\n", .{ ref, v }),
            .cmp => |c| {
                const op_str: []const u8 = switch (c.op) {
                    .eq => "==",
                    .ne => "!=",
                    .lt => "<",
                    .le => "<=",
                    .gt => ">",
                    .ge => ">=",
                };
                try self.writeFmt("v{d} = (v{d} {s} v{d});\n", .{ ref, c.left, op_str, c.right });
            },
            .log_not => |v| try self.writeFmt("v{d} = !v{d};\n", .{ ref, v }),
            .int_to_float => |v| try self.writeFmt("v{d} = (kira_int)(kira_float)v{d};\n", .{ ref, v }),
            .float_to_int => |v| try self.writeFmt("v{d} = (kira_int)v{d};\n", .{ ref, v }),
            .to_string => |_| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: to_string not implemented\\n\"); abort(); /* to_string */\n", .{ref}),
            .alloc_var => |a| {
                if (a.init_value) |iv| {
                    try self.writeFmt("v{d} = v{d}; /* var {s} */\n", .{ ref, iv, a.name });
                } else {
                    try self.writeFmt("v{d} = 0; /* var {s} */\n", .{ ref, a.name });
                }
            },
            .load_var => |v| try self.writeFmt("v{d} = v{d};\n", .{ ref, v }),
            .store_var => |s| try self.writeFmt("v{d} = v{d}; v{d} = 0;\n", .{ s.target, s.value, ref }),
            .call => |c| {
                // Emit indirect call through function-pointer cast
                try self.writeFmt("v{d} = ((kira_int(*)(", .{ref});
                for (0..c.args.len) |i| {
                    if (i > 0) try self.write(", ");
                    try self.write("kira_int");
                }
                try self.writeFmt("))v{d})(", .{c.callee});
                for (c.args, 0..) |a, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeFmt("v{d}", .{a});
                }
                try self.write(");\n");
            },
            .make_closure => |c| {
                try self.writeFmt("v{d} = (kira_int)0; /* closure func#{d} */\n", .{ ref, c.function_index });
            },
            .make_tuple => |elems| {
                try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: make_tuple({d}) not implemented\\n\"); abort();\n", .{ ref, elems.len });
            },
            .make_array => |elems| {
                try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: make_array[{d}] not implemented\\n\"); abort();\n", .{ ref, elems.len });
            },
            .make_record => |r| {
                if (r.type_name) |tn| {
                    try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: make_record {s} not implemented\\n\"); abort();\n", .{ ref, tn });
                } else {
                    try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: make_record not implemented\\n\"); abort();\n", .{ref});
                }
            },
            .make_variant => |v| {
                // Look up actual tag from module type declarations
                const tag = self.lookupVariantTag(v.type_name, v.variant_name);
                try self.writeFmt("v{d} = {d}; /* variant {s} tag */\n", .{ ref, tag, v.variant_name });
            },
            .tuple_get => |t| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: tuple_get.{d} not implemented\\n\"); abort();\n", .{ ref, t.index }),
            .field_get => |f| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: field_get .{s} not implemented\\n\"); abort();\n", .{ ref, f.field }),
            .index_get => |idx| try self.writeFmt("v{d} = 0; /* index_get v{d}[v{d}] */\n", .{ ref, idx.object, idx.index }),
            .array_len => |v| try self.writeFmt("v{d} = 0; /* array_len v{d} */\n", .{ ref, v }),
            .field_set => |f| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: field_set .{s} not implemented\\n\"); abort();\n", .{ ref, f.field }),
            .index_set => |_| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: index_set not implemented\\n\"); abort();\n", .{ref}),
            .get_tag => |v| try self.writeFmt("v{d} = v{d}; /* get_tag */\n", .{ ref, v }),
            .get_payload => |p| try self.writeFmt("v{d} = 0; /* get_payload v{d}.{d} — TODO: extract from ADT struct */\n", .{ ref, p.variant, p.field_index }),
            .wrap_some => |v| try self.writeFmt("v{d} = v{d}; /* wrap_some */\n", .{ ref, v }),
            .wrap_none => try self.writeFmt("v{d} = 0; /* wrap_none */\n", .{ref}),
            .wrap_ok => |v| try self.writeFmt("v{d} = v{d}; /* wrap_ok */\n", .{ ref, v }),
            .wrap_err => |v| try self.writeFmt("v{d} = v{d}; /* wrap_err */\n", .{ ref, v }),
            .unwrap => |v| try self.writeFmt("v{d} = v{d}; /* unwrap */\n", .{ ref, v }),
            .str_concat => |_| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: str_concat not implemented\\n\"); abort();\n", .{ref}),
            .param => |idx| {
                // Map parameter index to parameter name
                if (idx < func.params.len) {
                    try self.writeFmt("v{d} = {s};\n", .{ ref, func.params[idx].name });
                } else {
                    try self.writeFmt("v{d} = 0; /* param {d} */\n", .{ ref, idx });
                }
            },
            .capture => |idx| try self.writeFmt("v{d} = 0; /* capture {d} — TODO: load from closure env */\n", .{ ref, idx }),
            .store_param => |sp| {
                if (sp.param_index < func.params.len) {
                    try self.writeFmt("{s} = v{d}; /* TCO param reassign */\n", .{ func.params[sp.param_index].name, sp.value });
                }
            },
            .method_call => |mc| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: method_call .{s} not implemented\\n\"); abort();\n", .{ ref, mc.method }),
            .phi => |p| {
                // Phi nodes are handled by placing values in the predecessor blocks
                // For C, we just declare the variable (already done above)
                try self.writeFmt("/* phi: {d} incoming */\n", .{p.incoming.len});
            },
        }
    }

    // ----------------------------------------------------------------
    // Terminator emission
    // ----------------------------------------------------------------

    fn emitTerminator(self: *CCodeGen, term: *const Terminator) CodeGenError!void {
        try self.writeIndent();
        switch (term.*) {
            .ret => |v| {
                if (v) |val| {
                    try self.writeFmt("return v{d};\n", .{val});
                } else {
                    try self.write("return 0;\n");
                }
            },
            .jump => |b| try self.writeFmt("goto bb{d};\n", .{b}),
            .branch => |br| {
                try self.writeFmt("if (v{d}) goto bb{d}; else goto bb{d};\n", .{
                    br.condition,
                    br.then_block,
                    br.else_block,
                });
            },
            .switch_tag => |sw| {
                try self.writeFmt("switch (v{d}) {{\n", .{sw.value});
                self.indent_level += 1;
                for (sw.cases) |c| {
                    try self.writeIndent();
                    try self.writeFmt("case {d}: goto bb{d};\n", .{ c.tag, c.block });
                }
                try self.writeIndent();
                try self.writeFmt("default: goto bb{d};\n", .{sw.default});
                self.indent_level -= 1;
                try self.writeIndent();
                try self.write("}\n");
            },
            .unreachable_term => {
                try self.write("__builtin_unreachable();\n");
            },
        }
    }

    // ----------------------------------------------------------------
    // Helpers
    // ----------------------------------------------------------------

    /// Look up the tag value for a variant by searching the module's type declarations.
    fn lookupVariantTag(self: *const CCodeGen, type_name: ?[]const u8, variant_name: []const u8) u32 {
        const module = self.current_module orelse return 0;
        for (module.type_decls.items) |td| {
            switch (td.kind) {
                .sum_type => |st| {
                    // If type_name is provided, only search in the matching type
                    if (type_name) |tn| {
                        if (!std.mem.eql(u8, td.name, tn)) continue;
                    }
                    for (st.variants) |v| {
                        if (std.mem.eql(u8, v.name, variant_name)) return v.tag;
                    }
                },
                .product_type => {},
            }
        }
        return 0;
    }

    // ----------------------------------------------------------------
    // Output helpers
    // ----------------------------------------------------------------

    fn write(self: *CCodeGen, s: []const u8) CodeGenError!void {
        self.output.appendSlice(self.allocator, s) catch return CodeGenError.OutOfMemory;
    }

    fn writeFmt(self: *CCodeGen, comptime fmt: []const u8, args: anytype) CodeGenError!void {
        std.fmt.format(self.output.writer(self.allocator), fmt, args) catch return CodeGenError.OutOfMemory;
    }

    fn writeIndent(self: *CCodeGen) CodeGenError!void {
        for (0..self.indent_level) |_| {
            try self.write("    ");
        }
    }
};

// ============================================================
// Tests
// ============================================================

test "codegen arithmetic expression" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn add() { return 10 + 20; }
    var func = Function.init(alloc);
    func.name = "add";
    const blk = try func.addBlock(alloc);
    const a = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const b = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 20 } } });
    const c = try func.addInstruction(alloc, blk, .{ .op = .{ .int_binop = .{ .op = .add, .left = a, .right = b } } });
    func.setTerminator(blk, .{ .ret = c });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_add") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v0 = 10;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v1 = 20;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v2 = v0 + v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v2;") != null);
}

test "codegen function call" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn caller(f: i64) { return f(42); }
    const params = [_]Function.Param{.{ .name = "f", .value_ref = 0 }};
    var func = Function.init(alloc);
    func.name = "caller";
    func.params = &params;
    const blk = try func.addBlock(alloc);
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 0 } });
    const arg = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    const args = [_]ValueRef{arg};
    const result = try func.addInstruction(alloc, blk, .{ .op = .{ .call = .{ .callee = 0, .args = &args } } });
    func.setTerminator(blk, .{ .ret = result });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_caller(kira_int f)") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v0 = f;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v2;") != null);
}

test "codegen let binding" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_let() { let x = 42; return x; }
    var func = Function.init(alloc);
    func.name = "test_let";
    const blk = try func.addBlock(alloc);
    const val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    func.setTerminator(blk, .{ .ret = val });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "v0 = 42;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v0;") != null);
}

test "codegen if/else control flow" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    var func = Function.init(alloc);
    func.name = "test_if";
    const entry = try func.addBlock(alloc);
    const then_blk = try func.addBlock(alloc);
    const else_blk = try func.addBlock(alloc);

    const cond = try func.addInstruction(alloc, entry, .{ .op = .{ .const_bool = true } });
    func.setTerminator(entry, .{ .branch = .{
        .condition = cond,
        .then_block = then_blk,
        .else_block = else_blk,
    } });

    const then_val = try func.addInstruction(alloc, then_blk, .{ .op = .{ .const_int = .{ .value = 1 } } });
    func.setTerminator(then_blk, .{ .ret = then_val });

    const else_val = try func.addInstruction(alloc, else_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    func.setTerminator(else_blk, .{ .ret = else_val });

    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "if (v0) goto bb1; else goto bb2;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "bb1:") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "bb2:") != null);
}

test "codegen output matches interpreter for simple arithmetic" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // (2 + 3) * 4 = 20
    var func = Function.init(alloc);
    func.name = "calc";
    const blk = try func.addBlock(alloc);
    const v2 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 2 } } });
    const v3 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 3 } } });
    const sum = try func.addInstruction(alloc, blk, .{ .op = .{ .int_binop = .{ .op = .add, .left = v2, .right = v3 } } });
    const v4 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 4 } } });
    const product = try func.addInstruction(alloc, blk, .{ .op = .{ .int_binop = .{ .op = .mul, .left = sum, .right = v4 } } });
    func.setTerminator(blk, .{ .ret = product });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Verify the generated code computes the right thing structurally
    try std.testing.expect(std.mem.indexOf(u8, output, "v2 = v0 + v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v4 = v2 * v3;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v4;") != null);
}

test "codegen match on ADT with switch_tag" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_match(x) { match x { 0 => return 1; 1 => return 2; default => return 0; } }
    const params = [_]Function.Param{.{ .name = "x", .value_ref = 0 }};
    var func = Function.init(alloc);
    func.name = "test_match";
    func.params = &params;

    const entry = try func.addBlock(alloc);
    const case_a = try func.addBlock(alloc);
    const case_b = try func.addBlock(alloc);
    const default = try func.addBlock(alloc);

    // entry: param + switch
    const param = try func.addInstruction(alloc, entry, .{ .op = .{ .param = 0 } });
    const cases = [_]Terminator.SwitchCase{
        .{ .tag = 0, .block = case_a },
        .{ .tag = 1, .block = case_b },
    };
    func.setTerminator(entry, .{ .switch_tag = .{
        .value = param,
        .cases = &cases,
        .default = default,
    } });

    // case_a: return 1
    const v1 = try func.addInstruction(alloc, case_a, .{ .op = .{ .const_int = .{ .value = 1 } } });
    func.setTerminator(case_a, .{ .ret = v1 });

    // case_b: return 2
    const v2 = try func.addInstruction(alloc, case_b, .{ .op = .{ .const_int = .{ .value = 2 } } });
    func.setTerminator(case_b, .{ .ret = v2 });

    // default: return 0
    const v0 = try func.addInstruction(alloc, default, .{ .op = .{ .const_int = .{ .value = 0 } } });
    func.setTerminator(default, .{ .ret = v0 });

    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "switch (v0)") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "case 0: goto bb1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "case 1: goto bb2;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "default: goto bb3;") != null);
}

test "codegen for loop structure" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // Simulates lowered for loop: init -> cond -> body -> cond (or exit)
    var func = Function.init(alloc);
    func.name = "test_for";

    const init_blk = try func.addBlock(alloc);
    const cond_blk = try func.addBlock(alloc);
    const body_blk = try func.addBlock(alloc);
    const exit_blk = try func.addBlock(alloc);

    // init: idx = 0, jump cond
    const zero = try func.addInstruction(alloc, init_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    _ = try func.addInstruction(alloc, init_blk, .{ .op = .{ .alloc_var = .{ .name = "idx", .init_value = zero } } });
    func.setTerminator(init_blk, .{ .jump = cond_blk });

    // cond: idx < 10, branch(body, exit)
    const idx = try func.addInstruction(alloc, cond_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    const limit = try func.addInstruction(alloc, cond_blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const cmp = try func.addInstruction(alloc, cond_blk, .{ .op = .{ .cmp = .{ .op = .lt, .left = idx, .right = limit } } });
    func.setTerminator(cond_blk, .{ .branch = .{
        .condition = cmp,
        .then_block = body_blk,
        .else_block = exit_blk,
    } });

    // body: jump back to cond
    func.setTerminator(body_blk, .{ .jump = cond_blk });

    // exit: return 0
    const ret_val = try func.addInstruction(alloc, exit_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    func.setTerminator(exit_blk, .{ .ret = ret_val });

    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Verify loop structure
    try std.testing.expect(std.mem.indexOf(u8, output, "goto bb1;") != null); // init -> cond
    try std.testing.expect(std.mem.indexOf(u8, output, "if (v4) goto bb2; else goto bb3;") != null); // cond branch
    try std.testing.expect(std.mem.indexOf(u8, output, "bb2:") != null); // body
    try std.testing.expect(std.mem.indexOf(u8, output, "bb3:") != null); // exit
}

test "codegen effect function with IO" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // effect fn greet() { println("hello"); }
    var func = Function.init(alloc);
    func.name = "greet";
    func.is_effect = true;
    const blk = try func.addBlock(alloc);

    // String constant for the message
    const msg = try func.addInstruction(alloc, blk, .{
        .op = .{ .const_string = "hello" },
    });

    // Call println (method call emitted as placeholder)
    _ = try func.addInstruction(alloc, blk, .{
        .op = .{ .method_call = .{
            .object = msg,
            .method = "println",
            .args = &.{},
        } },
    });

    const void_val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_void = {} } });
    func.setTerminator(blk, .{ .ret = void_val });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Effect function is annotated
    try std.testing.expect(std.mem.indexOf(u8, output, "/* effect */") != null);
    // Preamble includes IO functions
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_println") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_print") != null);
    // Function exists
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_greet") != null);
}

test "codegen error propagation with try" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_try() { let x = try some_op(); return x; }
    var func = Function.init(alloc);
    func.name = "test_try";
    const blk = try func.addBlock(alloc);

    const val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    const unwrapped = try func.addInstruction(alloc, blk, .{ .op = .{ .unwrap = val } });
    func.setTerminator(blk, .{ .ret = unwrapped });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "/* unwrap */") != null);
}
