//! C code generation backend for Kira.
//!
//! Translates Kira IR into C source code that can be compiled with any
//! standard C compiler (gcc, clang).
//!
//! Each IR function becomes a C function. SSA values become local variables.
//! Basic blocks become labeled sections with goto-based control flow.
//!
//! Type-specific code generation:
//! - Function signatures use proper C types (int32_t, double, bool, etc.)
//!   derived from IR param type_name and return_type_name
//! - Record struct fields use proper C types from FieldDecl.type_name
//! - Constants use type-appropriate C declarations
//! - SSA variables use uniform kira_int internally for compound type compat
//!
//! Compound types are heap-allocated and referenced via intptr_t casts:
//! - Tuples: kira_int* with elements at [0..N)
//! - Arrays: kira_int* with length at [0], elements at [1..N]
//! - Records: kira_int* with fields at [0..N) indexed by declaration order
//! - Variants: kira_int* with tag at [0], payload fields at [1..N]
//! - Closures: kira_int* with function pointer at [0], captures at [1..N]
//! - Strings: char* cast through intptr_t; concat via malloc+strcat

const std = @import("std");
const Allocator = std.mem.Allocator;
const ir = @import("ir/ir.zig");
const Module = ir.Module;
const Function = ir.Function;
const Instruction = ir.Instruction;
const Terminator = ir.Terminator;
const ValueRef = ir.ValueRef;
const BlockId = ir.BlockId;

pub const CodeGenError = error{
    OutOfMemory,
    UnsupportedInstruction,
    InvalidIR,
};

/// C code generator that emits C source from Kira IR.
pub const CCodeGen = struct {
    allocator: Allocator,
    /// Output buffer for generated C code.
    output: std.ArrayListUnmanaged(u8),
    /// Current indentation level.
    indent_level: u32,
    /// Reference to the module being generated (set during generateModule).
    current_module: ?*const Module,

    pub fn init(allocator: Allocator) CCodeGen {
        return .{
            .allocator = allocator,
            .output = .{},
            .indent_level = 0,
            .current_module = null,
        };
    }

    pub fn deinit(self: *CCodeGen) void {
        self.output.deinit(self.allocator);
    }

    /// Get the generated C source code.
    pub fn getOutput(self: *const CCodeGen) []const u8 {
        return self.output.items;
    }

    /// Generate C code for an entire IR module.
    pub fn generateModule(self: *CCodeGen, module: *const Module) CodeGenError!void {
        self.current_module = module;
        try self.emitPreamble();
        try self.emitTypeDecls(module);
        try self.emitFunctionDeclarations(module);
        try self.emitConstants(module);
        for (module.functions.items) |*func| {
            try self.emitFunction(func);
        }
    }

    // ----------------------------------------------------------------
    // Preamble
    // ----------------------------------------------------------------

    fn emitPreamble(self: *CCodeGen) CodeGenError!void {
        try self.write("/* Generated by Kira compiler */\n");
        try self.write("#include <stdint.h>\n");
        try self.write("#include <stdbool.h>\n");
        try self.write("#include <stdio.h>\n");
        try self.write("#include <stdlib.h>\n");
        try self.write("#include <string.h>\n");
        try self.write("#include <math.h>\n\n");
        try self.write("/* Kira runtime types */\n");
        try self.write("typedef int64_t kira_int;\n");
        try self.write("typedef double kira_float;\n");
        try self.write("typedef bool kira_bool;\n");
        try self.write("typedef uint32_t kira_char;\n");
        try self.write("typedef const char* kira_string;\n");
        try self.write("typedef void kira_void;\n\n");
        try self.write("/* Kira runtime IO functions */\n");
        try self.write("static void kira_println(kira_string s) { printf(\"%s\\n\", s); }\n");
        try self.write("static void kira_print(kira_string s) { printf(\"%s\", s); }\n");
        try self.write("static void kira_println_int(kira_int n) { printf(\"%lld\\n\", (long long)n); }\n");
        try self.write("static void kira_print_int(kira_int n) { printf(\"%lld\", (long long)n); }\n");
        try self.write("static kira_string kira_int_to_string(kira_int n) {\n");
        try self.write("    char* s = (char*)malloc(32);\n");
        try self.write("    snprintf(s, 32, \"%lld\", (long long)n);\n");
        try self.write("    return s;\n");
        try self.write("}\n\n");
    }

    // ----------------------------------------------------------------
    // Type declarations
    // ----------------------------------------------------------------

    fn emitTypeDecls(self: *CCodeGen, module: *const Module) CodeGenError!void {
        if (module.type_decls.items.len == 0) return;
        try self.write("/* Type declarations */\n");
        for (module.type_decls.items) |td| {
            switch (td.kind) {
                .sum_type => |st| {
                    try self.write("/* Sum type: ");
                    try self.write(td.name);
                    try self.write(" */\n");
                    try self.write("typedef struct {\n");
                    self.indent_level += 1;
                    try self.writeIndent();
                    try self.write("uint32_t tag;\n");
                    // Find max field count across variants
                    var max_fields: u32 = 0;
                    for (st.variants) |v| {
                        if (v.field_count > max_fields) max_fields = v.field_count;
                    }
                    if (max_fields > 0) {
                        try self.writeIndent();
                        try self.writeFmt("kira_int fields[{d}];\n", .{max_fields});
                    }
                    self.indent_level -= 1;
                    try self.write("} kira_");
                    try self.write(td.name);
                    try self.write(";\n\n");

                    // Emit tag constants
                    for (st.variants) |v| {
                        try self.writeFmt("#define TAG_{s}_{s} {d}\n", .{ td.name, v.name, v.tag });
                    }
                    try self.write("\n");
                },
                .product_type => |pt| {
                    try self.write("/* Record type: ");
                    try self.write(td.name);
                    try self.write(" */\n");
                    try self.write("typedef struct {\n");
                    self.indent_level += 1;
                    for (pt.fields) |f| {
                        try self.writeIndent();
                        try self.write(kiraTypeToCType(f.type_name));
                        try self.writeFmt(" {s};\n", .{f.name});
                    }
                    self.indent_level -= 1;
                    try self.write("} kira_");
                    try self.write(td.name);
                    try self.write(";\n\n");
                },
            }
        }
    }

    // ----------------------------------------------------------------
    // Forward declarations
    // ----------------------------------------------------------------

    fn emitFunctionDeclarations(self: *CCodeGen, module: *const Module) CodeGenError!void {
        if (module.functions.items.len == 0) return;
        try self.write("/* Forward declarations */\n");
        for (module.functions.items) |*func| {
            try self.write(kiraTypeToCType(func.return_type_name));
            try self.write(" ");
            try self.emitFunctionName(func);
            try self.write("(");
            for (func.params, 0..) |p, i| {
                if (i > 0) try self.write(", ");
                try self.write(kiraTypeToCType(p.type_name));
                try self.writeFmt(" {s}", .{p.name});
            }
            if (func.params.len == 0) try self.write("void");
            try self.write(");\n");
        }
        try self.write("\n");
    }

    // ----------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------

    fn emitConstants(self: *CCodeGen, module: *const Module) CodeGenError!void {
        if (module.constants.items.len == 0) return;
        try self.write("/* Constants */\n");
        for (module.constants.items) |c| {
            switch (c.value) {
                .integer => |v| try self.writeFmt("static const int64_t kira_const_{s} = {d};\n", .{ c.name, v }),
                .float => |v| try self.writeFmt("static const double kira_const_{s} = {d};\n", .{ c.name, v }),
                .boolean => |b| try self.writeFmt("static const bool kira_const_{s} = {s};\n", .{ c.name, if (b) "true" else "false" }),
                .string => |s| {
                    try self.writeFmt("static const char* kira_const_{s} = \"", .{c.name});
                    try self.write(s);
                    try self.write("\";\n");
                },
                .char => |c_val| try self.writeFmt("static const uint32_t kira_const_{s} = {d};\n", .{ c.name, c_val }),
                .void_val => try self.writeFmt("static const int64_t kira_const_{s} = 0;\n", .{c.name}),
            }
        }
        try self.write("\n");
    }

    // ----------------------------------------------------------------
    // Function emission
    // ----------------------------------------------------------------

    fn emitFunction(self: *CCodeGen, func: *const Function) CodeGenError!void {
        // Function signature
        if (func.is_effect) try self.write("/* effect */ ");
        try self.write(kiraTypeToCType(func.return_type_name));
        try self.write(" ");
        try self.emitFunctionName(func);
        try self.write("(");
        for (func.params, 0..) |p, i| {
            if (i > 0) try self.write(", ");
            try self.write(kiraTypeToCType(p.type_name));
            try self.writeFmt(" {s}", .{p.name});
        }
        if (func.params.len == 0) try self.write("void");
        try self.write(") {\n");
        self.indent_level += 1;

        // Declare all SSA variables
        if (func.instructions.items.len > 0) {
            try self.writeIndent();
            try self.write("kira_int ");
            for (0..func.instructions.items.len) |i| {
                if (i > 0) try self.write(", ");
                try self.writeFmt("v{d}", .{i});
            }
            try self.write(";\n");
        }

        // Emit basic blocks
        for (func.blocks.items) |*blk| {
            try self.emitBlock(func, blk);
        }

        self.indent_level -= 1;
        try self.write("}\n\n");
    }

    fn emitFunctionName(self: *CCodeGen, func: *const Function) CodeGenError!void {
        if (func.name) |name| {
            try self.write("kira_");
            try self.write(name);
        } else {
            try self.write("kira_anon");
        }
    }

    fn emitBlock(self: *CCodeGen, func: *const Function, blk: *const ir.BasicBlock) CodeGenError!void {
        // Block label
        try self.writeIndent();
        try self.writeFmt("bb{d}:;\n", .{blk.id});

        // Instructions
        for (blk.instructions.items) |ref| {
            const inst = func.getInstruction(ref);
            try self.emitInstruction(func, ref, inst);
        }

        // Terminator
        try self.emitTerminator(func, &blk.terminator);
    }

    // ----------------------------------------------------------------
    // Instruction emission
    // ----------------------------------------------------------------

    fn emitInstruction(self: *CCodeGen, func: *const Function, ref: ValueRef, inst: *const Instruction) CodeGenError!void {
        try self.writeIndent();
        switch (inst.op) {
            .const_int => |c| try self.writeFmt("v{d} = {d};\n", .{ ref, c.value }),
            .const_float => |f| try self.writeFmt("v{d} = *(kira_int*)&(kira_float){{{d}}};\n", .{ ref, f }),
            .const_bool => |b| try self.writeFmt("v{d} = {d};\n", .{ ref, @as(u1, if (b) 1 else 0) }),
            .const_char => |c| try self.writeFmt("v{d} = {d};\n", .{ ref, c }),
            .const_void => try self.writeFmt("v{d} = 0;\n", .{ref}),
            .const_string => |s| try self.writeFmt("v{d} = (kira_int)(intptr_t)\"{s}\";\n", .{ ref, s }),
            .int_binop => |b| {
                const op_str: []const u8 = switch (b.op) {
                    .add => "+",
                    .sub => "-",
                    .mul => "*",
                    .div => "/",
                    .mod => "%",
                };
                try self.writeFmt("v{d} = v{d} {s} v{d};\n", .{ ref, b.left, op_str, b.right });
            },
            .float_binop => |b| {
                // Unpack i64 bit-patterns to double, operate, repack
                if (b.op == .mod) {
                    try self.writeFmt("{{ kira_float _a, _b, _r; memcpy(&_a, &v{d}, sizeof(kira_float)); memcpy(&_b, &v{d}, sizeof(kira_float)); _r = fmod(_a, _b); memcpy(&v{d}, &_r, sizeof(kira_float)); }}\n", .{ b.left, b.right, ref });
                } else {
                    const op_str: []const u8 = switch (b.op) {
                        .add => "+",
                        .sub => "-",
                        .mul => "*",
                        .div => "/",
                        .mod => unreachable,
                    };
                    try self.writeFmt("{{ kira_float _a, _b, _r; memcpy(&_a, &v{d}, sizeof(kira_float)); memcpy(&_b, &v{d}, sizeof(kira_float)); _r = _a {s} _b; memcpy(&v{d}, &_r, sizeof(kira_float)); }}\n", .{ b.left, b.right, op_str, ref });
                }
            },
            .int_neg => |v| try self.writeFmt("v{d} = -v{d};\n", .{ ref, v }),
            .float_neg => |v| try self.writeFmt("{{ kira_float _f; memcpy(&_f, &v{d}, sizeof(kira_float)); _f = -_f; memcpy(&v{d}, &_f, sizeof(kira_float)); }}\n", .{ v, ref }),
            .cmp => |c| {
                const op_str: []const u8 = switch (c.op) {
                    .eq => "==",
                    .ne => "!=",
                    .lt => "<",
                    .le => "<=",
                    .gt => ">",
                    .ge => ">=",
                };
                try self.writeFmt("v{d} = (v{d} {s} v{d});\n", .{ ref, c.left, op_str, c.right });
            },
            .log_not => |v| try self.writeFmt("v{d} = !v{d};\n", .{ ref, v }),
            .int_to_float => |v| try self.writeFmt("{{ kira_float _f = (kira_float)v{d}; memcpy(&v{d}, &_f, sizeof(kira_float)); }}\n", .{ v, ref }),
            .float_to_int => |v| try self.writeFmt("{{ kira_float _f; memcpy(&_f, &v{d}, sizeof(kira_float)); v{d} = (kira_int)_f; }}\n", .{ v, ref }),
            .to_string => |v| {
                // Convert integer to string via snprintf
                try self.writeFmt("{{ char* _s = (char*)malloc(32); snprintf(_s, 32, \"%lld\", (long long)v{d}); v{d} = (kira_int)(intptr_t)_s; }}\n", .{ v, ref });
            },
            .alloc_var => |a| {
                if (a.init_value) |iv| {
                    try self.writeFmt("v{d} = v{d}; /* var {s} */\n", .{ ref, iv, a.name });
                } else {
                    try self.writeFmt("v{d} = 0; /* var {s} */\n", .{ ref, a.name });
                }
            },
            .load_var => |v| try self.writeFmt("v{d} = v{d};\n", .{ ref, v }),
            .store_var => |s| try self.writeFmt("v{d} = v{d}; v{d} = 0;\n", .{ s.target, s.value, ref }),
            .call => |c| {
                // Emit indirect call through function-pointer cast
                try self.writeFmt("v{d} = ((kira_int(*)(", .{ref});
                for (0..c.args.len) |i| {
                    if (i > 0) try self.write(", ");
                    try self.write("kira_int");
                }
                try self.writeFmt("))v{d})(", .{c.callee});
                for (c.args, 0..) |a, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeFmt("v{d}", .{a});
                }
                try self.write(");\n");
            },
            .make_closure => |c| {
                // Layout: [function_ptr][capture0][capture1]...
                try self.writeFmt("{{ kira_int* _c = (kira_int*)malloc({d} * sizeof(kira_int)); _c[0] = (kira_int)(intptr_t)&", .{c.captures.len + 1});
                // Emit the function name reference
                const module = self.current_module;
                if (module) |m| {
                    if (c.function_index < m.functions.items.len) {
                        const target_func = &m.functions.items[c.function_index];
                        try self.emitFunctionName(target_func);
                    } else {
                        try self.write("kira_anon");
                    }
                } else {
                    try self.write("kira_anon");
                }
                try self.write("; ");
                for (c.captures, 0..) |cap, i| {
                    try self.writeFmt("_c[{d}] = v{d}; ", .{ i + 1, cap });
                }
                try self.writeFmt("v{d} = (kira_int)(intptr_t)_c; }}\n", .{ref});
            },
            .make_tuple => |elems| {
                // Heap-allocate a kira_int array, store elements, cast to kira_int
                try self.writeFmt("{{ kira_int* _t = (kira_int*)malloc({d} * sizeof(kira_int)); ", .{elems.len});
                for (elems, 0..) |elem, i| {
                    try self.writeFmt("_t[{d}] = v{d}; ", .{ i, elem });
                }
                try self.writeFmt("v{d} = (kira_int)(intptr_t)_t; }}\n", .{ref});
            },
            .make_array => |elems| {
                // Layout: [length][elem0][elem1]... — length at index 0, elements at 1..N
                try self.writeFmt("{{ kira_int* _a = (kira_int*)malloc({d} * sizeof(kira_int)); _a[0] = {d}; ", .{ elems.len + 1, elems.len });
                for (elems, 0..) |elem, i| {
                    try self.writeFmt("_a[{d}] = v{d}; ", .{ i + 1, elem });
                }
                try self.writeFmt("v{d} = (kira_int)(intptr_t)_a; }}\n", .{ref});
            },
            .make_record => |r| {
                // Heap-allocate a kira_int array for fields, cast to kira_int
                try self.writeFmt("{{ kira_int* _r = (kira_int*)malloc({d} * sizeof(kira_int)); ", .{r.field_values.len});
                for (r.field_values, 0..) |fv, i| {
                    try self.writeFmt("_r[{d}] = v{d}; ", .{ i, fv });
                }
                if (r.type_name) |tn| {
                    try self.writeFmt("v{d} = (kira_int)(intptr_t)_r; }} /* record {s} */\n", .{ ref, tn });
                } else {
                    try self.writeFmt("v{d} = (kira_int)(intptr_t)_r; }}\n", .{ref});
                }
            },
            .make_variant => |v| {
                const tag = self.lookupVariantTag(v.type_name, v.variant_name);
                const payload_len: usize = if (v.payload) |p| p.len else 0;
                // Layout: [tag][field0][field1]... — always heap-allocated for uniform get_tag
                try self.writeFmt("{{ kira_int* _v = (kira_int*)malloc({d} * sizeof(kira_int)); _v[0] = {d}; ", .{ payload_len + 1, tag });
                if (v.payload) |payload| {
                    for (payload, 0..) |p, i| {
                        try self.writeFmt("_v[{d}] = v{d}; ", .{ i + 1, p });
                    }
                }
                try self.writeFmt("v{d} = (kira_int)(intptr_t)_v; }} /* variant {s} */\n", .{ ref, v.variant_name });
            },
            .tuple_get => |t| try self.writeFmt("v{d} = ((kira_int*)(intptr_t)v{d})[{d}];\n", .{ ref, t.tuple, t.index }),
            .field_get => |f| {
                // Look up field index from type declarations, fallback to linear search
                const field_idx = self.lookupFieldIndex(f.field);
                try self.writeFmt("v{d} = ((kira_int*)(intptr_t)v{d})[{d}]; /* .{s} */\n", .{ ref, f.object, field_idx, f.field });
            },
            .index_get => |idx| {
                // Elements start at index 1 (index 0 is length)
                try self.writeFmt("v{d} = ((kira_int*)(intptr_t)v{d})[v{d} + 1];\n", .{ ref, idx.object, idx.index });
            },
            .array_len => |v| {
                // Length is stored at index 0
                try self.writeFmt("v{d} = ((kira_int*)(intptr_t)v{d})[0];\n", .{ ref, v });
            },
            .field_set => |f| {
                const field_idx = self.lookupFieldIndex(f.field);
                try self.writeFmt("((kira_int*)(intptr_t)v{d})[{d}] = v{d}; v{d} = 0; /* .{s} = */\n", .{ f.object, field_idx, f.value, ref, f.field });
            },
            .index_set => |idx| {
                // Elements start at index 1 (index 0 is length)
                try self.writeFmt("((kira_int*)(intptr_t)v{d})[v{d} + 1] = v{d}; v{d} = 0;\n", .{ idx.object, idx.index, idx.value, ref });
            },
            .get_tag => |v| {
                // Tag is at index 0 of the heap-allocated variant struct
                try self.writeFmt("v{d} = ((kira_int*)(intptr_t)v{d})[0]; /* get_tag */\n", .{ ref, v });
            },
            .get_payload => |p| {
                // Payload fields start at index 1
                try self.writeFmt("v{d} = ((kira_int*)(intptr_t)v{d})[{d}]; /* get_payload */\n", .{ ref, p.variant, p.field_index + 1 });
            },
            .wrap_some => |v| try self.writeFmt("v{d} = v{d}; /* wrap_some */\n", .{ ref, v }),
            .wrap_none => try self.writeFmt("v{d} = 0; /* wrap_none */\n", .{ref}),
            .wrap_ok => |v| try self.writeFmt("v{d} = v{d}; /* wrap_ok */\n", .{ ref, v }),
            .wrap_err => |v| try self.writeFmt("v{d} = v{d}; /* wrap_err */\n", .{ ref, v }),
            .unwrap => |v| try self.writeFmt("v{d} = v{d}; /* unwrap */\n", .{ ref, v }),
            .str_concat => |sc| {
                // Concatenate string parts using runtime helper
                if (sc.parts.len == 0) {
                    try self.writeFmt("v{d} = (kira_int)(intptr_t)\"\";\n", .{ref});
                } else if (sc.parts.len == 1) {
                    try self.writeFmt("v{d} = v{d};\n", .{ ref, sc.parts[0] });
                } else {
                    // Compute total length, allocate, then copy parts
                    try self.writeFmt("{{ size_t _len = 0; ", .{});
                    for (sc.parts) |p| {
                        try self.writeFmt("_len += strlen((const char*)(intptr_t)v{d}); ", .{p});
                    }
                    try self.write("char* _s = (char*)malloc(_len + 1); _s[0] = '\\0'; ");
                    for (sc.parts) |p| {
                        try self.writeFmt("strcat(_s, (const char*)(intptr_t)v{d}); ", .{p});
                    }
                    try self.writeFmt("v{d} = (kira_int)(intptr_t)_s; }}\n", .{ref});
                }
            },
            .param => |idx| {
                // Map parameter index to parameter name
                if (idx < func.params.len) {
                    try self.writeFmt("v{d} = {s};\n", .{ ref, func.params[idx].name });
                } else {
                    try self.writeFmt("v{d} = 0; /* param {d} */\n", .{ ref, idx });
                }
            },
            .capture => |idx| {
                // Load captured value from closure environment (passed as hidden first param)
                // Captures start at index 1 (index 0 is function pointer)
                try self.writeFmt("v{d} = ((kira_int*)(intptr_t)_env)[{d}]; /* capture {d} */\n", .{ ref, idx + 1, idx });
            },
            .store_param => |sp| {
                if (sp.param_index < func.params.len) {
                    try self.writeFmt("{s} = v{d}; /* TCO param reassign */\n", .{ func.params[sp.param_index].name, sp.value });
                }
            },
            .method_call => |mc| try self.writeFmt("v{d} = 0; fprintf(stderr, \"runtime: method_call .{s} not implemented\\n\"); abort();\n", .{ ref, mc.method }),
            .phi => |p| {
                // Phi nodes are handled by placing values in the predecessor blocks
                // For C, we just declare the variable (already done above)
                try self.writeFmt("/* phi: {d} incoming */\n", .{p.incoming.len});
            },
        }
    }

    // ----------------------------------------------------------------
    // Terminator emission
    // ----------------------------------------------------------------

    fn emitTerminator(self: *CCodeGen, func: *const Function, term: *const Terminator) CodeGenError!void {
        try self.writeIndent();
        switch (term.*) {
            .ret => |v| {
                const is_void = std.mem.eql(u8, func.return_type_name, "void");
                if (is_void) {
                    try self.write("return;\n");
                } else if (v) |val| {
                    try self.writeFmt("return v{d};\n", .{val});
                } else {
                    try self.write("return 0;\n");
                }
            },
            .jump => |b| try self.writeFmt("goto bb{d};\n", .{b}),
            .branch => |br| {
                try self.writeFmt("if (v{d}) goto bb{d}; else goto bb{d};\n", .{
                    br.condition,
                    br.then_block,
                    br.else_block,
                });
            },
            .switch_tag => |sw| {
                try self.writeFmt("switch (v{d}) {{\n", .{sw.value});
                self.indent_level += 1;
                for (sw.cases) |c| {
                    try self.writeIndent();
                    try self.writeFmt("case {d}: goto bb{d};\n", .{ c.tag, c.block });
                }
                try self.writeIndent();
                try self.writeFmt("default: goto bb{d};\n", .{sw.default});
                self.indent_level -= 1;
                try self.writeIndent();
                try self.write("}\n");
            },
            .unreachable_term => {
                try self.write("__builtin_unreachable();\n");
            },
        }
    }

    // ----------------------------------------------------------------
    // Helpers
    // ----------------------------------------------------------------

    /// Look up the tag value for a variant by searching the module's type declarations.
    fn lookupVariantTag(self: *const CCodeGen, type_name: ?[]const u8, variant_name: []const u8) u32 {
        const module = self.current_module orelse return 0;
        for (module.type_decls.items) |td| {
            switch (td.kind) {
                .sum_type => |st| {
                    // If type_name is provided, only search in the matching type
                    if (type_name) |tn| {
                        if (!std.mem.eql(u8, td.name, tn)) continue;
                    }
                    for (st.variants) |v| {
                        if (std.mem.eql(u8, v.name, variant_name)) return v.tag;
                    }
                },
                .product_type => {},
            }
        }
        return 0;
    }

    /// Look up the index of a field by name, searching all product type declarations.
    fn lookupFieldIndex(self: *const CCodeGen, field_name: []const u8) u32 {
        const module = self.current_module orelse return 0;
        for (module.type_decls.items) |td| {
            switch (td.kind) {
                .product_type => |pt| {
                    for (pt.fields) |f| {
                        if (std.mem.eql(u8, f.name, field_name)) return f.index;
                    }
                },
                .sum_type => {},
            }
        }
        return 0;
    }

    // ----------------------------------------------------------------
    // Type mapping
    // ----------------------------------------------------------------

    /// Map a Kira source-level type name to the corresponding C type string.
    fn kiraTypeToCType(type_name: []const u8) []const u8 {
        if (std.mem.eql(u8, type_name, "i8")) return "int8_t";
        if (std.mem.eql(u8, type_name, "i16")) return "int16_t";
        if (std.mem.eql(u8, type_name, "i32")) return "int32_t";
        if (std.mem.eql(u8, type_name, "i64")) return "int64_t";
        if (std.mem.eql(u8, type_name, "i128")) return "__int128";
        if (std.mem.eql(u8, type_name, "u8")) return "uint8_t";
        if (std.mem.eql(u8, type_name, "u16")) return "uint16_t";
        if (std.mem.eql(u8, type_name, "u32")) return "uint32_t";
        if (std.mem.eql(u8, type_name, "u64")) return "uint64_t";
        if (std.mem.eql(u8, type_name, "u128")) return "unsigned __int128";
        if (std.mem.eql(u8, type_name, "f32")) return "float";
        if (std.mem.eql(u8, type_name, "f64")) return "double";
        if (std.mem.eql(u8, type_name, "bool")) return "bool";
        if (std.mem.eql(u8, type_name, "string")) return "const char*";
        if (std.mem.eql(u8, type_name, "char")) return "uint32_t";
        if (std.mem.eql(u8, type_name, "void")) return "void";
        return "int64_t"; // fallback for compound/unknown types
    }

    // ----------------------------------------------------------------
    // Output helpers
    // ----------------------------------------------------------------

    fn write(self: *CCodeGen, s: []const u8) CodeGenError!void {
        self.output.appendSlice(self.allocator, s) catch return CodeGenError.OutOfMemory;
    }

    fn writeFmt(self: *CCodeGen, comptime fmt: []const u8, args: anytype) CodeGenError!void {
        std.fmt.format(self.output.writer(self.allocator), fmt, args) catch return CodeGenError.OutOfMemory;
    }

    fn writeIndent(self: *CCodeGen) CodeGenError!void {
        for (0..self.indent_level) |_| {
            try self.write("    ");
        }
    }
};

// ============================================================
// Tests
// ============================================================

test "codegen arithmetic expression" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn add() { return 10 + 20; }
    var func = Function.init(alloc);
    func.name = "add";
    const blk = try func.addBlock(alloc);
    const a = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const b = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 20 } } });
    const c = try func.addInstruction(alloc, blk, .{ .op = .{ .int_binop = .{ .op = .add, .left = a, .right = b } } });
    func.setTerminator(blk, .{ .ret = c });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_add") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v0 = 10;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v1 = 20;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v2 = v0 + v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v2;") != null);
}

test "codegen function call" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn caller(f: i64) { return f(42); }
    const params = [_]Function.Param{.{ .name = "f", .value_ref = 0 }};
    var func = Function.init(alloc);
    func.name = "caller";
    func.params = &params;
    const blk = try func.addBlock(alloc);
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 0 } });
    const arg = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    const args = [_]ValueRef{arg};
    const result = try func.addInstruction(alloc, blk, .{ .op = .{ .call = .{ .callee = 0, .args = &args } } });
    func.setTerminator(blk, .{ .ret = result });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_caller(int64_t f)") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v0 = f;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v2;") != null);
}

test "codegen let binding" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_let() { let x = 42; return x; }
    var func = Function.init(alloc);
    func.name = "test_let";
    const blk = try func.addBlock(alloc);
    const val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    func.setTerminator(blk, .{ .ret = val });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "v0 = 42;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v0;") != null);
}

test "codegen if/else control flow" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    var func = Function.init(alloc);
    func.name = "test_if";
    const entry = try func.addBlock(alloc);
    const then_blk = try func.addBlock(alloc);
    const else_blk = try func.addBlock(alloc);

    const cond = try func.addInstruction(alloc, entry, .{ .op = .{ .const_bool = true } });
    func.setTerminator(entry, .{ .branch = .{
        .condition = cond,
        .then_block = then_blk,
        .else_block = else_blk,
    } });

    const then_val = try func.addInstruction(alloc, then_blk, .{ .op = .{ .const_int = .{ .value = 1 } } });
    func.setTerminator(then_blk, .{ .ret = then_val });

    const else_val = try func.addInstruction(alloc, else_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    func.setTerminator(else_blk, .{ .ret = else_val });

    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "if (v0) goto bb1; else goto bb2;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "bb1:") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "bb2:") != null);
}

test "codegen output matches interpreter for simple arithmetic" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // (2 + 3) * 4 = 20
    var func = Function.init(alloc);
    func.name = "calc";
    const blk = try func.addBlock(alloc);
    const v2 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 2 } } });
    const v3 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 3 } } });
    const sum = try func.addInstruction(alloc, blk, .{ .op = .{ .int_binop = .{ .op = .add, .left = v2, .right = v3 } } });
    const v4 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 4 } } });
    const product = try func.addInstruction(alloc, blk, .{ .op = .{ .int_binop = .{ .op = .mul, .left = sum, .right = v4 } } });
    func.setTerminator(blk, .{ .ret = product });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Verify the generated code computes the right thing structurally
    try std.testing.expect(std.mem.indexOf(u8, output, "v2 = v0 + v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "v4 = v2 * v3;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return v4;") != null);
}

test "codegen match on ADT with switch_tag" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_match(x) { match x { 0 => return 1; 1 => return 2; default => return 0; } }
    const params = [_]Function.Param{.{ .name = "x", .value_ref = 0 }};
    var func = Function.init(alloc);
    func.name = "test_match";
    func.params = &params;

    const entry = try func.addBlock(alloc);
    const case_a = try func.addBlock(alloc);
    const case_b = try func.addBlock(alloc);
    const default = try func.addBlock(alloc);

    // entry: param + switch
    const param = try func.addInstruction(alloc, entry, .{ .op = .{ .param = 0 } });
    const cases = [_]Terminator.SwitchCase{
        .{ .tag = 0, .block = case_a },
        .{ .tag = 1, .block = case_b },
    };
    func.setTerminator(entry, .{ .switch_tag = .{
        .value = param,
        .cases = &cases,
        .default = default,
    } });

    // case_a: return 1
    const v1 = try func.addInstruction(alloc, case_a, .{ .op = .{ .const_int = .{ .value = 1 } } });
    func.setTerminator(case_a, .{ .ret = v1 });

    // case_b: return 2
    const v2 = try func.addInstruction(alloc, case_b, .{ .op = .{ .const_int = .{ .value = 2 } } });
    func.setTerminator(case_b, .{ .ret = v2 });

    // default: return 0
    const v0 = try func.addInstruction(alloc, default, .{ .op = .{ .const_int = .{ .value = 0 } } });
    func.setTerminator(default, .{ .ret = v0 });

    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "switch (v0)") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "case 0: goto bb1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "case 1: goto bb2;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "default: goto bb3;") != null);
}

test "codegen for loop structure" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // Simulates lowered for loop: init -> cond -> body -> cond (or exit)
    var func = Function.init(alloc);
    func.name = "test_for";

    const init_blk = try func.addBlock(alloc);
    const cond_blk = try func.addBlock(alloc);
    const body_blk = try func.addBlock(alloc);
    const exit_blk = try func.addBlock(alloc);

    // init: idx = 0, jump cond
    const zero = try func.addInstruction(alloc, init_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    _ = try func.addInstruction(alloc, init_blk, .{ .op = .{ .alloc_var = .{ .name = "idx", .init_value = zero } } });
    func.setTerminator(init_blk, .{ .jump = cond_blk });

    // cond: idx < 10, branch(body, exit)
    const idx = try func.addInstruction(alloc, cond_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    const limit = try func.addInstruction(alloc, cond_blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const cmp = try func.addInstruction(alloc, cond_blk, .{ .op = .{ .cmp = .{ .op = .lt, .left = idx, .right = limit } } });
    func.setTerminator(cond_blk, .{ .branch = .{
        .condition = cmp,
        .then_block = body_blk,
        .else_block = exit_blk,
    } });

    // body: jump back to cond
    func.setTerminator(body_blk, .{ .jump = cond_blk });

    // exit: return 0
    const ret_val = try func.addInstruction(alloc, exit_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    func.setTerminator(exit_blk, .{ .ret = ret_val });

    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Verify loop structure
    try std.testing.expect(std.mem.indexOf(u8, output, "goto bb1;") != null); // init -> cond
    try std.testing.expect(std.mem.indexOf(u8, output, "if (v4) goto bb2; else goto bb3;") != null); // cond branch
    try std.testing.expect(std.mem.indexOf(u8, output, "bb2:") != null); // body
    try std.testing.expect(std.mem.indexOf(u8, output, "bb3:") != null); // exit
}

test "codegen effect function with IO" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // effect fn greet() { println("hello"); }
    var func = Function.init(alloc);
    func.name = "greet";
    func.is_effect = true;
    const blk = try func.addBlock(alloc);

    // String constant for the message
    const msg = try func.addInstruction(alloc, blk, .{
        .op = .{ .const_string = "hello" },
    });

    // Call println (method call emitted as placeholder)
    _ = try func.addInstruction(alloc, blk, .{
        .op = .{ .method_call = .{
            .object = msg,
            .method = "println",
            .args = &.{},
        } },
    });

    const void_val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_void = {} } });
    func.setTerminator(blk, .{ .ret = void_val });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Effect function is annotated
    try std.testing.expect(std.mem.indexOf(u8, output, "/* effect */") != null);
    // Preamble includes IO functions
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_println") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_print") != null);
    // Function exists
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_greet") != null);
}

test "codegen error propagation with try" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_try() { let x = try some_op(); return x; }
    var func = Function.init(alloc);
    func.name = "test_try";
    const blk = try func.addBlock(alloc);

    const val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    const unwrapped = try func.addInstruction(alloc, blk, .{ .op = .{ .unwrap = val } });
    func.setTerminator(blk, .{ .ret = unwrapped });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "/* unwrap */") != null);
}

test "codegen tuple construction and access" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_tuple() { let t = (10, 20, 30); return t.1; }
    var func = Function.init(alloc);
    func.name = "test_tuple";
    const blk = try func.addBlock(alloc);

    const a = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const b = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 20 } } });
    const c = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 30 } } });
    const elems = [_]ValueRef{ a, b, c };
    const tuple = try func.addInstruction(alloc, blk, .{ .op = .{ .make_tuple = &elems } });
    const elem1 = try func.addInstruction(alloc, blk, .{ .op = .{ .tuple_get = .{ .tuple = tuple, .index = 1 } } });
    func.setTerminator(blk, .{ .ret = elem1 });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Tuple construction: heap-alloc + fill
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(3 * sizeof(kira_int))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_t[0] = v0;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_t[1] = v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_t[2] = v2;") != null);
    // Tuple access: index into the heap array
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v3)[1]") != null);
}

test "codegen record construction and field access" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // Add type declaration for Point record
    _ = try module.addTypeDecl(.{
        .name = "Point",
        .kind = .{ .product_type = .{
            .fields = &[_]ir.FieldDecl{
                .{ .name = "x", .index = 0 },
                .{ .name = "y", .index = 1 },
            },
        } },
    });

    // fn test_record() { let p = Point { x: 10, y: 20 }; return p.y; }
    var func = Function.init(alloc);
    func.name = "test_record";
    const blk = try func.addBlock(alloc);

    const x = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const y = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 20 } } });
    const names = [_][]const u8{ "x", "y" };
    const vals = [_]ValueRef{ x, y };
    const record = try func.addInstruction(alloc, blk, .{ .op = .{ .make_record = .{
        .type_name = "Point",
        .field_names = &names,
        .field_values = &vals,
    } } });
    const field_y = try func.addInstruction(alloc, blk, .{ .op = .{ .field_get = .{ .object = record, .field = "y" } } });
    func.setTerminator(blk, .{ .ret = field_y });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Record construction
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(2 * sizeof(kira_int))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_r[0] = v0;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_r[1] = v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "record Point") != null);
    // Field access: index 1 for "y"
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v2)[1]") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "/* .y */") != null);
}

test "codegen array construction, index, and length" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_array() { let a = [1, 2, 3]; let len = a.len; return a[1]; }
    var func = Function.init(alloc);
    func.name = "test_array";
    const blk = try func.addBlock(alloc);

    const e0 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 1 } } });
    const e1 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 2 } } });
    const e2 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 3 } } });
    const elems = [_]ValueRef{ e0, e1, e2 };
    const arr = try func.addInstruction(alloc, blk, .{ .op = .{ .make_array = &elems } });
    const len = try func.addInstruction(alloc, blk, .{ .op = .{ .array_len = arr } });
    _ = len;
    const idx = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 1 } } });
    const elem = try func.addInstruction(alloc, blk, .{ .op = .{ .index_get = .{ .object = arr, .index = idx } } });
    func.setTerminator(blk, .{ .ret = elem });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Array construction: length at [0], elements at [1..N]
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(4 * sizeof(kira_int))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_a[0] = 3;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_a[1] = v0;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_a[2] = v1;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_a[3] = v2;") != null);
    // Array length: index 0
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v3)[0]") != null);
    // Index access: elements offset by 1
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v3)[v5 + 1]") != null);
}

test "codegen ADT variant with payload" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // Add Option type declaration
    _ = try module.addTypeDecl(.{
        .name = "Option",
        .kind = .{ .sum_type = .{
            .variants = &[_]ir.VariantDecl{
                .{ .name = "Some", .tag = 0, .field_count = 1 },
                .{ .name = "None", .tag = 1, .field_count = 0 },
            },
        } },
    });

    // fn test_variant() { let x = Some(42); let tag = get_tag(x); let val = get_payload(x, 0); return val; }
    var func = Function.init(alloc);
    func.name = "test_variant";
    const blk = try func.addBlock(alloc);

    const val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    const payload = [_]ValueRef{val};
    const variant = try func.addInstruction(alloc, blk, .{ .op = .{ .make_variant = .{
        .type_name = "Option",
        .variant_name = "Some",
        .payload = &payload,
    } } });
    const tag = try func.addInstruction(alloc, blk, .{ .op = .{ .get_tag = variant } });
    _ = tag;
    const extracted = try func.addInstruction(alloc, blk, .{ .op = .{ .get_payload = .{ .variant = variant, .field_index = 0 } } });
    func.setTerminator(blk, .{ .ret = extracted });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Variant construction: heap-alloc [tag][payload...]
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(2 * sizeof(kira_int))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_v[0] = 0;") != null); // tag = 0 (Some)
    try std.testing.expect(std.mem.indexOf(u8, output, "_v[1] = v0;") != null); // payload
    try std.testing.expect(std.mem.indexOf(u8, output, "/* variant Some */") != null);
    // get_tag: read index 0
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v1)[0]") != null);
    // get_payload: read index 1 (field_index 0 + 1)
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v1)[1]") != null);
}

test "codegen unit variant (no payload)" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    _ = try module.addTypeDecl(.{
        .name = "Option",
        .kind = .{ .sum_type = .{
            .variants = &[_]ir.VariantDecl{
                .{ .name = "Some", .tag = 0, .field_count = 1 },
                .{ .name = "None", .tag = 1, .field_count = 0 },
            },
        } },
    });

    // fn test_none() { let x = None; return get_tag(x); }
    var func = Function.init(alloc);
    func.name = "test_none";
    const blk = try func.addBlock(alloc);

    const none = try func.addInstruction(alloc, blk, .{ .op = .{ .make_variant = .{
        .type_name = "Option",
        .variant_name = "None",
        .payload = null,
    } } });
    const tag = try func.addInstruction(alloc, blk, .{ .op = .{ .get_tag = none } });
    func.setTerminator(blk, .{ .ret = tag });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Unit variant: still heap-allocated with just the tag
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(1 * sizeof(kira_int))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_v[0] = 1;") != null); // tag = 1 (None)
    try std.testing.expect(std.mem.indexOf(u8, output, "/* variant None */") != null);
}

test "codegen closure construction" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // Inner closure function
    var inner = Function.init(alloc);
    inner.name = "adder_inner";
    const inner_blk = try inner.addBlock(alloc);
    const ret_val = try inner.addInstruction(alloc, inner_blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    inner.setTerminator(inner_blk, .{ .ret = ret_val });
    const inner_idx = try module.addFunction(inner);

    // Outer function that creates the closure
    var outer = Function.init(alloc);
    outer.name = "make_adder";
    const blk = try outer.addBlock(alloc);
    const captured_val = try outer.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const captures = [_]ValueRef{captured_val};
    const closure = try outer.addInstruction(alloc, blk, .{ .op = .{ .make_closure = .{
        .function_index = inner_idx,
        .captures = &captures,
    } } });
    outer.setTerminator(blk, .{ .ret = closure });
    _ = try module.addFunction(outer);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Closure: heap-alloc [func_ptr][captures...]
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(2 * sizeof(kira_int))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "&kira_adder_inner") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "_c[1] = v0;") != null);
}

test "codegen string concat" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_concat() { return "hello" ++ " " ++ "world"; }
    var func = Function.init(alloc);
    func.name = "test_concat";
    const blk = try func.addBlock(alloc);

    const s1 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_string = "hello" } });
    const s2 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_string = " world" } });
    const parts = [_]ValueRef{ s1, s2 };
    const result = try func.addInstruction(alloc, blk, .{ .op = .{ .str_concat = .{ .parts = &parts } } });
    func.setTerminator(blk, .{ .ret = result });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // String concat: compute length, malloc, strcat
    try std.testing.expect(std.mem.indexOf(u8, output, "strlen") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "strcat") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(_len + 1)") != null);
}

test "codegen to_string" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_to_string() { return to_string(42); }
    var func = Function.init(alloc);
    func.name = "test_to_string";
    const blk = try func.addBlock(alloc);

    const val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 42 } } });
    const str = try func.addInstruction(alloc, blk, .{ .op = .{ .to_string = val } });
    func.setTerminator(blk, .{ .ret = str });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // to_string: snprintf into heap buffer
    try std.testing.expect(std.mem.indexOf(u8, output, "snprintf") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "malloc(32)") != null);
}

test "codegen field_set on record" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    _ = try module.addTypeDecl(.{
        .name = "Point",
        .kind = .{ .product_type = .{
            .fields = &[_]ir.FieldDecl{
                .{ .name = "x", .index = 0 },
                .{ .name = "y", .index = 1 },
            },
        } },
    });

    // fn test_set() { var p = Point{x: 1, y: 2}; p.x = 99; return p.x; }
    var func = Function.init(alloc);
    func.name = "test_set";
    const blk = try func.addBlock(alloc);

    const x = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 1 } } });
    const y = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 2 } } });
    const names = [_][]const u8{ "x", "y" };
    const vals = [_]ValueRef{ x, y };
    const record = try func.addInstruction(alloc, blk, .{ .op = .{ .make_record = .{
        .type_name = "Point",
        .field_names = &names,
        .field_values = &vals,
    } } });
    const new_val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 99 } } });
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .field_set = .{
        .object = record,
        .field = "x",
        .value = new_val,
    } } });
    const read_x = try func.addInstruction(alloc, blk, .{ .op = .{ .field_get = .{ .object = record, .field = "x" } } });
    func.setTerminator(blk, .{ .ret = read_x });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // field_set: write to index 0 for field "x"
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v2)[0] = v3;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "/* .x = */") != null);
}

test "codegen index_set on array" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn test_index_set() { var a = [10, 20]; a[0] = 99; return a[0]; }
    var func = Function.init(alloc);
    func.name = "test_index_set";
    const blk = try func.addBlock(alloc);

    const e0 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 10 } } });
    const e1 = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 20 } } });
    const elems = [_]ValueRef{ e0, e1 };
    const arr = try func.addInstruction(alloc, blk, .{ .op = .{ .make_array = &elems } });
    const idx = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 0 } } });
    const new_val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_int = .{ .value = 99 } } });
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .index_set = .{
        .object = arr,
        .index = idx,
        .value = new_val,
    } } });
    const read = try func.addInstruction(alloc, blk, .{ .op = .{ .index_get = .{ .object = arr, .index = idx } } });
    func.setTerminator(blk, .{ .ret = read });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // index_set: elements offset by 1
    try std.testing.expect(std.mem.indexOf(u8, output, "((kira_int*)(intptr_t)v2)[v3 + 1] = v4;") != null);
}

test "codegen preamble includes int_to_string helper" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_int_to_string") != null);
}

test "codegen typed function signatures" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn distance(x: f64, y: f64) -> f64
    const params = [_]Function.Param{
        .{ .name = "x", .value_ref = 0, .type_name = "f64" },
        .{ .name = "y", .value_ref = 1, .type_name = "f64" },
    };
    var func = Function.init(alloc);
    func.name = "distance";
    func.params = &params;
    func.return_type_name = "f64";
    const blk = try func.addBlock(alloc);
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 0 } });
    const p1 = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 1 } });
    func.setTerminator(blk, .{ .ret = p1 });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Forward declaration has proper types
    try std.testing.expect(std.mem.indexOf(u8, output, "double kira_distance(double x, double y);") != null);
    // Definition also has proper types
    try std.testing.expect(std.mem.indexOf(u8, output, "double kira_distance(double x, double y) {") != null);
}

test "codegen typed record fields" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();

    // Record with typed fields
    _ = try module.addTypeDecl(.{
        .name = "Vec2",
        .kind = .{ .product_type = .{
            .fields = &[_]ir.FieldDecl{
                .{ .name = "x", .index = 0, .type_name = "f64" },
                .{ .name = "y", .index = 1, .type_name = "f64" },
            },
        } },
    });

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Record fields use proper C types
    try std.testing.expect(std.mem.indexOf(u8, output, "double x;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "double y;") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "kira_Vec2") != null);
}

test "codegen typed constants" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();

    _ = try module.addConstant(.{ .name = "PI", .value = .{ .float = 3.14159 } });
    _ = try module.addConstant(.{ .name = "MAX", .value = .{ .integer = 100 } });
    _ = try module.addConstant(.{ .name = "DEBUG", .value = .{ .boolean = true } });
    _ = try module.addConstant(.{ .name = "NAME", .value = .{ .string = "kira" } });

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "static const double kira_const_PI") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "static const int64_t kira_const_MAX") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "static const bool kira_const_DEBUG = true") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "static const char* kira_const_NAME") != null);
}

test "codegen void return type" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // effect fn greet() -> void
    var func = Function.init(alloc);
    func.name = "greet";
    func.is_effect = true;
    func.return_type_name = "void";
    const blk = try func.addBlock(alloc);
    const void_val = try func.addInstruction(alloc, blk, .{ .op = .{ .const_void = {} } });
    func.setTerminator(blk, .{ .ret = void_val });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Void function signature
    try std.testing.expect(std.mem.indexOf(u8, output, "void kira_greet(void)") != null);
    // Void return (no value)
    try std.testing.expect(std.mem.indexOf(u8, output, "return;\n") != null);
}

test "codegen mixed typed params" {
    const backing = std.testing.allocator;
    var module = Module.init(backing);
    defer module.deinit();
    const alloc = module.allocator();

    // fn process(name: string, count: i32, flag: bool) -> i32
    const params = [_]Function.Param{
        .{ .name = "name", .value_ref = 0, .type_name = "string" },
        .{ .name = "count", .value_ref = 1, .type_name = "i32" },
        .{ .name = "flag", .value_ref = 2, .type_name = "bool" },
    };
    var func = Function.init(alloc);
    func.name = "process";
    func.params = &params;
    func.return_type_name = "i32";
    const blk = try func.addBlock(alloc);
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 0 } });
    const p1 = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 1 } });
    _ = try func.addInstruction(alloc, blk, .{ .op = .{ .param = 2 } });
    func.setTerminator(blk, .{ .ret = p1 });
    _ = try module.addFunction(func);

    var gen = CCodeGen.init(backing);
    defer gen.deinit();
    try gen.generateModule(&module);

    const output = gen.getOutput();
    // Forward declaration with mixed types
    try std.testing.expect(std.mem.indexOf(u8, output, "int32_t kira_process(const char* name, int32_t count, bool flag);") != null);
    // Definition with mixed types
    try std.testing.expect(std.mem.indexOf(u8, output, "int32_t kira_process(const char* name, int32_t count, bool flag) {") != null);
}
